version: '3'

services:
  postgres:
    image: postgres:11
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: test
      POSTGRES_USER: noverde
      POSTGRES_PASSWORD: noverde

  dynamodb:
    image: amazon/dynamodb-local
    restart: on-failure
    ports:
      - "8000:8000"
