[tool.stela]
default_environment = "test"
config_file_extension = "TOML"

[tool.coverage.report]
fail_under = 40

[tool.pytest]
addopts = '--pydocstyle'

[tool.black]
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \venv
    | \.aws-sam
    | _build
    | buck-out
    | build
    | dist
    | alembic
    | node_modules
  )/
)
'''

[tool.poetry]
name = "noverde-cookiecutter"
version = "0.1.0"
description = "This project contains all boilerplate you need to create a new microservice."
authors = ["Noverde <devs@noverde.com.br>"]

[tool.poetry.dependencies]
python = "^3.7"
aws_lambda_context = "*"
cookiecutter = "*"
loguru = "*"
marshmallow = "*"
python-json-logger = "*"
psycopg2 = "*"
sentry-sdk = "*"
SQLAlchemy = "*"
stela = "*"

[tool.poetry.dev-dependencies]
alembic = "*"
black = {version = "*", allow-prereleases = true}
factory_boy = "*"
freezegun = "*"
pytest = "*"
pytest-black = "*"
pytest-cov = "*"
pytest-mock = "*"
pytest-mypy = "*"
pytest-postgresql = "*"
pytest-pydocstyle = "*"
pytest-watch = "*"
pytest-xdist ="*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"