[logger]
level = "DEBUG"
use_json_format = false

[database.sql]
url = "postgres://noverde:noverde@localhost/cookiecutter_develop"
echo = true

[sentry]
endpoint = ""

[noverde.mydomain.settings]
name = "noverde_mydomain_settings"
active = true