use_cookie_path = true

[logger]
level = "DEBUG"
use_json_format = false

[database.sql]
url = "postgres://noverde:noverde@localhost/noverde_test_project_develop"
echo = true

[database.nosql]
table_name = "cookie_test"
capacity.read = 1
capacity.write = 1

[cors]
allow_origin = "*"

[sentry]
endpoint = ""

[noverde.mydomain.settings]
active = true