version: "3.3"
services:
  sam:
    image: lambda_local/sam-cli-local
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/var/opt:ro
      - $HOME/.aws:/root/.aws:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  stepfunctions:
    image: amazon/aws-stepfunctions-local
    ports:
      - "8083:8083"
  dynamodb:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      lambda-local:
    ports:
      - "8000:8000"

networks:
  lambda-local:
    external: true
