version: "3.3"
services:
  sam:
    image: {{ cookiecutter.project_name_slug }}:dev
    build: .
    env_file:
      - .env
    depends_on:
      - dynamodb
      - stepfunctions
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - .:/var/opt:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  stepfunctions:
    image: amazon/aws-stepfunctions-local
    ports:
      - "8083:8083"
  dynamodb:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      lambda-local:
    ports:
      - "8000:8000"

networks:
  lambda-local:
    external: true
