"""Add noverde unique field

Revision ID: aaf0165ccf17
Revises: dd04094968da
Create Date: 2020-04-10 19:26:00.364124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf0165ccf17'
down_revision = 'dd04094968da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mydomain_model', sa.Column('noverde_unique_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mydomain_model', 'noverde_unique_field')
    # ### end Alembic commands ###
