name: deploy
on:
  push:
    branches:
      - develop
      - staging
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.7
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v1
      - name: Deploy to Develop
        if: github.ref == 'refs/heads/develop'
        run: |
          make deploy
        env:
          ENVIRONMENT: development
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS }}{% endraw %}
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          make deploy
        env:
          ENVIRONMENT: staging
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS }}{% endraw %}
      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'
        run: |
          make deploy
        env:
          ENVIRONMENT: production
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS }}{% endraw %}
