name: pull_request
on: [pull_request]
jobs:
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: {{ cookiecutter.python_version }}
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v1
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8000
          cors: '*'
      - name: Install Python dependencies
        run: |
          make install
      - name: Run CI Tests
        run: |
          make ci
        env:
          AWS_DEFAULT_REGION: us-east-1
          PYTHONPATH: {{cookiecutter.model_name_slug}}/
          AWS_ACCESS_KEY_ID: 1234
          AWS_SECRET_ACCESS_KEY: 1234
