name: tests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.8
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v1
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8000
          cors: '*'
      - name: Install Python dependencies
        run: |
          make install
      - name: Run Tests
        run: |
          make ci
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: 1234
          AWS_SECRET_ACCESS_KEY: 1234


