name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.7
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v1
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: '11'
          postgresql db: 'test'
          postgresql user: 'noverde'
          postgresql password: 'noverde'
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8000
          cors: '*'
      - name: Install Python dependencies
        run: |
          make install
      - name: Run Tests (with DynamoDB)
        run: |
          make ci
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: 1234
          AWS_SECRET_ACCESS_KEY: 1234
      - name: Run Tests (with RDS)
        run: |
          make ci
        env:
          COOKIECUTTER_CONFIG: cookie_rds.yml
          AWS_DEFAULT_REGION: us-east-1
      - name: Run Tests (both Databases)
        run: |
          make ci
        env:
          COOKIECUTTER_CONFIG: cookie_both.yml
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: 1234
          AWS_SECRET_ACCESS_KEY: 1234
      - name: Run Tests (no Databases)
        run: |
          make ci
        env:
          COOKIECUTTER_CONFIG: cookie_none.yml
          AWS_DEFAULT_REGION: us-east-1
      - name: Run Tests (Minimal install)
        run: |
          make ci
        env:
          COOKIECUTTER_CONFIG: cookie_minimal.yml
          AWS_DEFAULT_REGION: us-east-1
      - name: Create Release
        if: github.ref == 'refs/heads/master'
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}

